"""Check that headline numbers in the manuscript match the released artifacts.

The paper promises that every reported statistic is regenerated by a released
script. This checks the headline values directly against the JSON and CSV those
scripts write, so a stale number cannot survive a revision unnoticed.

Run from anywhere:  python analysis/verify_manuscript_numbers.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
TEX = ROOT / "IEEE_Access_Submission" / "main.tex"


def load_json(name):
    p = RESULTS / name
    return json.loads(p.read_text()) if p.exists() else None


def main() -> None:
    tex = TEX.read_text(encoding="utf-8")

    # Table bodies are pulled in with \input, so their numbers are not literally
    # in main.tex.  Splice them in before checking, otherwise a value that moved
    # from the running text into a table looks like it went missing.
    for m in re.finditer(r"\\input\{([^}]+)\}", tex):
        ref = m.group(1)
        for cand in (TEX.parent / ref, TEX.parent / (ref + ".tex"),
                     RESULTS / Path(ref).name, RESULTS / (Path(ref).name + ".tex")):
            if cand.exists() and cand.is_file():
                tex += "\n" + cand.read_text(encoding="utf-8", errors="replace")
                break

    # LaTeX writes thousands separators as 19{,}527; normalize so a plain
    # "19,527" from the artifact still matches.
    tex = tex.replace("{,}", ",")
    checks: list[tuple[str, str, object, bool]] = []

    def check(label, needle, source_value, fmt="{}"):
        want = fmt.format(source_value)
        checks.append((label, want, needle in tex, want in tex))

    # --- predictive benchmark -------------------------------------------
    bm = load_json("benchmark_metrics_expanded.json")
    if bm:
        for label, key, fmt in [
            ("AUROC at KIBA threshold", "auroc", "{:.4f}"),
            ("AUPRC at KIBA threshold", "auprc", "{:.4f}"),
            ("balanced accuracy", "balanced_accuracy", "{:.4f}"),
            ("MCC", "mcc", "{:.4f}"),
            ("concordance index", "concordance_index", "{:.4f}"),
            ("Spearman", "spearman_rho", "{:.4f}"),
            ("active base rate", "base_rate", "{:.4f}"),
        ]:
            v = fmt.format(bm[key])
            checks.append((label, v, True, v in tex))

    # --- overlap / saturation -------------------------------------------
    ov = load_json("overlap_chance_summary.json")
    if ov:
        checks.append(("atom overlap mean", f"{ov['atom_overlap_mean']:.3f}",
                       True, f"{ov['atom_overlap_mean']:.3f}" in tex))
        checks.append(("atom chance level", f"{ov['atom_base_rate_mean']:.3f}",
                       True, f"{ov['atom_base_rate_mean']:.3f}" in tex))

    # --- interaction maps ------------------------------------------------
    ci = load_json("contact_information_summary.json")
    if ci:
        vd = ci["variance_decomposition"]
        checks.append(("residue main effect %",
                       f"{100*vd['frac_residue_main_effect']:.1f}",
                       True, f"{100*vd['frac_residue_main_effect']:.1f}" in tex))
        checks.append(("interaction %",
                       f"{100*vd['frac_ligand_by_residue_interaction']:.1f}",
                       True, f"{100*vd['frac_ligand_by_residue_interaction']:.1f}" in tex))
        cl = ci["classification"]
        for label, key in [("probe AUROC", "auroc_from_attention_profile"),
                           ("descriptor AUROC", "auroc_from_descriptors"),
                           ("model score AUROC", "auroc_model_score"),
                           ("ECFP AUROC", "auroc_ecfp_baseline")]:
            v = f"{cl[key]:.3f}"
            checks.append((label, v, True, v in tex))
        r2 = f"{ci['affinity_regression']['r2_from_attention_profile']:.3f}"
        checks.append(("affinity R2", r2, True, r2 in tex))

    # --- ablation ---------------------------------------------------------
    ab = load_json("attention_ablation_summary.json")
    if ab:
        for cond in ("intact", "cross_attention_half", "cross_attention_off"):
            if cond in ab:
                v = f"{ab[cond]['concordance_index']:.4f}"
                checks.append((f"{cond} CI", v, True, v in tex))
                v = f"{ab[cond]['rmse']:.4f}"
                checks.append((f"{cond} RMSE", v, True, v in tex))

    # --- efficiency -------------------------------------------------------
    ef = load_json("efficiency_profile.json")
    if ef:
        tot = ef["parameters"]["total_parameters"] / 1e6
        checks.append(("total parameters (M)", f"{tot:.1f}", True, f"{tot:.1f}" in tex))
        frac = 100 * ef["parameters"]["interaction_map_parameter_share"]
        checks.append(("fusion share %", f"{frac:.1f}", True, f"{frac:.1f}" in tex))
        sc = ef.get("scaling", {}).get("protein_length")
        if sc:
            v = f"{sc['slope_ms_per_unit']:.3f}"
            checks.append(("ms per residue", v, True, v in tex))

    # --- assay-type sensitivity ------------------------------------------
    ah = load_json("assay_type_hierarchy_summary.json")
    if ah and ah.get("status") == "ok":
        for label, key in [("records", "n_records"), ("pairs", "n_pairs"),
                           ("multi-type pairs", "n_pairs_multi_type"),
                           ("type changed", "n_pairs_type_changed"),
                           ("potent current", "n_potent_current_rule"),
                           ("potent priority", "n_potent_priority_rule")]:
            v = f"{ah[key]:,}"
            checks.append((label, v, True, v in tex or str(ah[key]) in tex))

    # --- docking ----------------------------------------------------------
    dk = load_json("docking_retrieval_summary.json")
    if dk:
        for label, key in [("Vina AUROC", "vina"), ("model AUROC", "deepdta_ibam"),
                           ("ECFP AUROC", "ecfp_nearest_active")]:
            v = f"{dk['metrics'][key]['auroc']:.3f}"
            checks.append((f"docking {label}", v, True, v in tex))

    missing = [c for c in checks if not c[3]]
    print(f"{len(checks) - len(missing)} of {len(checks)} headline values "
          f"found verbatim in the manuscript\n")
    if missing:
        print("not found in main.tex (stale, rounded differently, or not yet written):")
        for label, want, _, _ in missing:
            print(f"  {label:34s} artifact says {want}")
    else:
        print("every checked value matches its artifact")

    # Placeholders must not survive.
    tbd = re.findall(r"\\tbd\{([^}]*)\}", tex)
    if tbd:
        print(f"\n{len(tbd)} unresolved placeholder(s):")
        for t in tbd:
            print(f"  {t}")
        sys.exit(1)


if __name__ == "__main__":
    main()
